export enum ErrorCode {
  INTERNAL_SEVER_ERROR = "INTERNAL_SEVER_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  NOT_EMPTY = "NOT_EMPTY",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  RESTAURANT_NOT_FOUND = "RESTAURANT_NOT_FOUND",
}
